a_set = {1, 'two', 3, 4, 'ten', 5, 5, 3,3, 'four', 'two'}
print(a_set)
print(type(a_set))
others = ['Cherop', 'Helen', 'Lina']
my_set = set(others)
print(my_set)
friends = ('ronald', 'langat', 'wangereka', 'kabogo', 'bownface')
your_friends = set(friends)
print(your_friends)
new_set = set()
print(new_set)
print(type(new_set))
not_sure = {}
print(type(not_sure))
print('='*100)
print(my_set)
my_set.add('Betty')
print(my_set)
my_set.add('Lina')
print(my_set)
my_set.update({'Lina', 'Betty', 'Beva', 'Daphine', 'Chepko'})
print(my_set)
my_set.update({'Sara', 'Sharon', 'Chemutai'}, {'Jane', 'Lucy'})
print(my_set)
print('='*100)
my_set.discard('Lucy')
print(my_set)
my_set.discard('Isabella')
print(my_set)
my_set.remove('Sharon')
print(my_set)
# my_set.remove('Sharon') Returns a KeyError
my_set.pop()
print(my_set)
my_set.clear()
print(my_set)  # same to re-instanciating it. ie my_set = set()
print('='*100)
some_set = {2, 4, 5, 9, 12, 21, 30, 51, 76, 127, 195}
print(30 in some_set)
print(31 in some_set)
other_set = {1, 2, 3, 5, 6, 8, 9, 12, 15, 17, 18, 21}
print('Union', some_set.union(other_set))
print('Intersection', some_set.intersection(other_set))
print('A difference B', some_set.difference(other_set))
print('B difference A', other_set.difference(some_set))
print(other_set.difference(some_set) == some_set.difference(other_set))
print('Symmetric Difference', some_set.symmetric_difference(other_set))
print('Reverse Symmetric Difference', other_set.symmetric_difference(some_set))
print(other_set.symmetric_difference(some_set) == some_set.symmetric_difference(other_set))
print('='*100)
a_set = {1, 2, 3}
b_set = {1, 2, 3, 4}
print(a_set.issubset(b_set))
print(b_set.issuperset(a_set))
a_set.add(5)
print(a_set.issubset(b_set))
